<?php
/**
 * Implements hook_permission()
 */
function impport_permission() {
  return array(
    'administer uploader' => array(
      'title' => t('Administer Uploader'),
      'description' => t('Allow the following roles to upload csv files to the server.'),
    ),
  );
}
 
/**
 * Implements hook_menu()
 */
function impport_menu() {
  $items['file-uploader'] = array(
    'title' => 'Upload a File',
    'type' => MENU_CALLBACK,
    'description' => 'Import a csv',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('impport_import_form'),
    'access arguments' => array('administer uploader'),
  );
  
    $items['admin/config/impport'] = array(
    'title' => 'Import CSV Config',
    'description' => 'Exemple de configuration de import CSV ',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('impport_admin_form'),
    'access arguments' => array('administer site configuration'),
    'file' => 'impport.admin.inc',
    'type' => MENU_NORMAL_ITEM,
  );
  
  $items['filter'] = array(
    'title' => 'Table Filter',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('impport_list_form'),
    'access arguments' => array("access content"),
    'type' => MENU_CALLBACK
  );

  return $items;
}


function impport_list_form($form, &$form_state) {
	
	$header = array(
		array('data' => t('Nom'),'field' => 'title'),
		array('data' => t('Valeur'),'field' => 'field_valeur'),
		array('data' => t('ref'),'field' => 'field_ref'),
	  );
	  
	  
    $form = array();
		 
		
	// First we create a form element with AJAX enabled
	$form['ajax_example'] = array
	(
		'#type' => 'select',
		'#title' => t('Choisir un Filtre'),
		// Note that I am setting the value and the display of the elements to be the same, for convenience sake in our callback function
		'#options' => array(0 => t('Select something'), 1 => t('Show Nom'), 2 => t('Show Valeur'), 3 => t('Show Ref')),
		'#prefix' => '<div id="after_ajax_element_wrapper">',
		'#suffix' => '</div>',
		'#ajax' => array
		(
			'callback' => 'after_ajax_ajax_callback',
			'event' => 'change',
		),
	);
 
	// Next we add our JavaScript file, named after_ajax.js. This file
	// lives in the /js folder inside our module:
	/*
	$form['#attached']['js'] = array
	(
		array
		(
			'type'  => 'file',
			'data' => drupal_get_path('module', 'impport') . '/js/after_ajax.js',
		),
	);
	*/
      	
	// Query all of the nids of a particular content type.
    $nids = db_select('node', 'n')
    ->fields('n', array('nid'))
    ->condition('type', 'accessoire', '=')
    ->execute()
    ->fetchCol();
  
    // Get all of the article nodes.
    $nodes = node_load_multiple($nids);

	
	
	$form['table'] = array(
	  '#theme' => 'myo_template',
	  '#header' => $header,
	  '#rows' => $nodes
	);
	
	//$form['results'] = theme('my_template', $vars); 
  
	//return $output;
	return $form;
  }
 
  
  /**
 * Listserv Subscribe form validate handler.
 */
/*function impport_list_form_validate($form, &$form_state) {
  $email = $form_state['values']['email'];
  // Verify that the email address is valid.
  if (!valid_email_address($email)) {
    form_set_error('email', t('You must provide a valid email address.'));
  }
}*/

/**
 * Impliments hook_form_FORMID_alter.
 */
/*function impport_list_form_alter(&$form, &$form_state, $form_id) {
  $form['submit']['#ajax'] = array(
    'callback' => 'impport_list_subscribe_callback',
    'wrapper' => 'listserv-subscribe-form',
  );
}
*/

/**
 * Callback for heymp_form_listserv_subscribe_form_alter
 */
function after_ajax_ajax_callback($form, &$form_state) {
  // First, we initialize our $commands array. This array will
	// contain each of the commands we want to fire for our
	// #AJAX callback:
 	$commands = array();
 
	// Next, we create our insert function that will insert our updated content
	// back into the page. To do this, we use the system provided
	// ajax_command_html() function. We pass this function two values:
	// 1) Our AJAX wrapper (that we defined as the #prefix and #suffix of our form element)
	// 2) The rendered HTML that needs to be inserted into the wrapper in the page.
	$commands[] = ajax_command_html('#after_ajax_element_wrapper', render($form['ajax_example']));
   
    $commands[] = ajax_command_invoke('.hi1','show');
	$commands[] = ajax_command_invoke('.hi2','show');
	$commands[] = ajax_command_invoke('.hi3','show');
	
	if($form_state['values']['ajax_example']==1){
			$commands[] = ajax_command_invoke('.hi2','hide');
			$commands[] = ajax_command_invoke('.hi3','hide');
			              
	}
	if($form_state['values']['ajax_example']==2){
			$commands[] = ajax_command_invoke('.hi1','hide');
			$commands[] = ajax_command_invoke('.hi3','hide');
	}
	if($form_state['values']['ajax_example']==3){
			$commands[] = ajax_command_invoke('.hi1','hide');
			$commands[] = ajax_command_invoke('.hi2','hide');
	}
	
	//$commands[] = ajax_command_restripe('table');
	/*
	if($form_state['values']['ajax_example']==1){
		    
			$commands[] = ajax_command_remove('.hi2');
			$commands[] = ajax_command_remove('.hi3');
			              
	}
	if($form_state['values']['ajax_example']==2){
			$commands[] = ajax_command_remove('.hi1');
			$commands[] = ajax_command_remove('.hi2');
	}
	if($form_state['values']['ajax_example']==3){
			$commands[] = ajax_command_remove('.hi1');
			$commands[] = ajax_command_remove('.hi2');
	}
    */
	// Next, we will use the system provided ajax_command_alert() function as an example to show it's
	// working:
	//$commands[] = ajax_command_alert(t($form_state['values']['ajax_example']));
 
	// Next we will include a custom function that we will call ourselves in our JavaScript file:
	/*
	$commands[] = array
	(
		// The command will be used in our JavaScript file (see next section)
		'command' => 'afterAjaxCallbackExample',
		// We pass the value that the user selected in the select element to our
		// JavaScript function:
		'selectedValue' => $form_state['values']['ajax_example'],
	);
    */
	// And finally, we will return all of our commands to the system to be executed:
	return array('#type' => 'ajax', '#commands' => $commands);
}





/**
 * Listserv Subscribe form submit handler.
 */
/*function impport_list_form_submit($form, &$form_state) {
  $email = $form_state['values']['email'];
 // listserv_listserv_subscription($email, 'subscribe');
}*/
  
  function impport_theme($existing, $type, $theme, $path){
    return array(
        'myo_template' => array(
            'template' => 'myo-template',
			'variables' => array(
                'header' => NULL,
				'rows' => NULL,
            ),
        ),
    );
    }
  
  /*function impport_list_form_submit($form, &$form_state) {
  $form_state['filters']['nom'] = $form_state['values']['filter_nom'];
  }*/


/**
 * @file
 * (config_exemple.admin.inc) Exemple de formulaires de configuration
 */

function impport_admin_form($form, &$form_state) {
 
  $form['impport'] = array(
    '#type' => 'textfield',
    '#title' => 'Chemin dossier contenant image à importer',
    '#default_value' => variable_get('impport_configuration', 'C:\Users\amine\Downloads'),
    '#size' => 100,
    '#maxlength' => 128,
    '#required' => TRUE,
  );
  
  $form['impporti'] = array(
    '#type' => 'textfield',
    '#title' => 'Chemin dossier ou seront uploder les image',
    '#default_value' => variable_get('impporti_configuration', 'access/picture/'),
    '#size' => 100,
    '#maxlength' => 128,
    '#required' => TRUE,
  );
 
  $form['submit'] = array(
      '#type' => 'submit',
      '#value' => 'Mettre à jour',
      '#submit' => array('impport_admin_submit'),
  );
 
  return $form;
 
}


function impport_admin_submit($form, &$form_state) {
 
  //$variable_persitante = variable_get('impport_configuration', NULL);
  // $variable_persitante = variable_get('impport_configuration', 'C:\Users\amine\Downloads');
   //$variable_persitantes = variable_get('impporti_configuration', 'private://access/picture/');

  $valeur_transmise = $form_state['values']['impport'];
  $valeur_transmises = $form_state['values']['impporti'];
  //if ($variable_persitante != $valeur_transmise) {
    variable_set('impport_configuration', $valeur_transmise);
	variable_set('impporti_configuration', $valeur_transmises);
    drupal_set_message('Variable mise à jour avec ' . $valeur_transmise . $valeur_transmises);
  /*}
  else {
    drupal_set_message('La variable persistante est inchangée');
  }*/

}




/**
 * Builds a form that will allow users to upload csv files
 * 
 * @see
 *   hook_menu()
 */
function impport_import_form($form, $form_state) {
  $form['notes'] = array(
    '#type' => 'markup',
    '#markup' => '<div class="import-notes">A few notes when uploading. <ul><li>Make sure the file is in a .csv format.</li><li>Columns should be in *this* order</li><li>Be sure to click the "Upload" button when you select a csv.</li></ul></div>',
    '#upload_location' => 'public://tmp/',
  );
  $form['import'] = array(
    '#title' => t('Import'),
    '#type' => 'managed_file',
    '#description' => t('The uploaded csv will be imported and temporarily saved.'),
    '#upload_location' => 'public://tmp/',
    '#upload_validators' => array(
      'file_validate_extensions' => array('csv'),
    ),
  );
  $form['submit'] = array (
    '#type' => 'submit',
    '#value' => t('Import'),
  );
  return $form;
}





/**
 * Submit handler for module_name_import_form()
 */
function impport_import_form_submit($form, $form_state) {
  // Check to make sure that the file was uploaded to the server properly
  $uri = db_query("SELECT uri FROM {file_managed} WHERE fid = :fid", array(
    ':fid' => $form_state['input']['import']['fid'],
  ))->fetchField();
  if(!empty($uri)) {
    if(file_exists(drupal_realpath($uri))) { 
      // Open the csv
      $handle = fopen(drupal_realpath($uri), "r");
      // Go through each row in the csv and run a function on it. In this case we are parsing by '|' (pipe) characters.
      // If you want commas are any other character, replace the pipe with it.
      while (($data = fgetcsv($handle, 0, ',', '"')) !== FALSE) {
        $operations[] = array(
          'impport_import_batch_processing',  // The function to run on each row
          array($data),  // The row in the csv
        );
      }
 
      // Once everything is gathered and ready to be processed... well... process it!
      $batch = array(
        'title' => t('Importing CSV...'),
        'operations' => $operations,  // Runs all of the queued processes from the while loop above.
        'finished' => 'impport_import_finished', // Function to run when the import is successful
        'error_message' => t('The installation has encountered an error.'),
        'progress_message' => t('Imported @current of @total products.'),
      );
      batch_set($batch);
      fclose($handle);    
    }
  }
  else {
    drupal_set_message(t('There was an error uploading your file. Please contact a System administator.'), 'error');
  }
}



/**
 * This function runs the batch processing and creates nodes with then given information
 * @see
 * module_name_import_form_submit()
 */
function impport_import_batch_processing($data) {
	
  // Lets make the variables more readable.
  //$file_directorie='C:\Users\amine\Downloads';
  $file_directorie=variable_get('impport_configuration', 'C:\Users\amine\Downloads');
  $pathp=variable_get('impporti_configuration', 'access/picture/');
  //Create the directory if it does not already exist, otherwise check the permissions
  $file_private='private://'.$pathp;
  file_prepare_directory($file_private, FILE_CREATE_DIRECTORY);
 
  
  $nom = $data[0];
  $field_valeur = $data[1];
  $field_ref = $data[2];
  $pictuure=$data[3];
  // Find out if the node already exists by looking up its serial number. Each serial number should be unique. You can use whatever you want.
  $nid = db_query("SELECT DISTINCT n.nid FROM {node} n " . 
    "INNER JOIN {field_data_field_ref} s ON s.revision_id = n.vid AND s.entity_id = n.nid " .
    "WHERE field_ref_value = :serial", array(
      ':serial' => $field_ref,
    ))->fetchField();
  if(!empty($nid)) {
    // The node exists! Load it.
	 global $user;
    $node = node_load($nid);
 
    // Change the values. No need to update the serial number though.
    $node->title = $nom;
    $node->field_valeur['und'][0]['value'] = $field_valeur;
    $node->field_valeur['und'][0]['safe_value'] = check_plain($field_valeur);
	
	//$file_name='Koala.jpg';
	
	$file_temp = file_get_contents($file_directorie.'\\'.$pictuure);

	// Saves a file to the specified destination and creates a database entry.
	$file_temp = file_save_data($file_temp, $file_private.$pictuure, FILE_EXISTS_RENAME);

	$node->field_pic = array(
	  'und' => array(
		0 => array(
		  'fid' => $file_temp->fid,
		  'filename' => $file_temp->filename,
		  'filemime' => $file_temp->filemime,
		  'uid' => $user->uid,
		  'uri' => $file_temp->uri,
		  'status' => 1,
		  'display' => 1
		)
	  )
	);	
	
    node_save($node);
  }
  else {
    // The node does not exist! Create it.
    global $user;
    $node = new StdClass();
    $node->type = 'accessoire'; // Choose your type
    $node->status = 1; // Sets to published automatically, 0 will be unpublished
    $node->title = $nom;
    $node->uid = $user->uid;		
    $node->field_valeur['und'][0]['value'] = $field_valeur;
    $node->field_valeur['und'][0]['safe_value'] = check_plain($field_valeur);
    $node->language = 'und';
    
    $node->field_ref['und'][0]['value'] = $field_ref;
    $node->field_ref['und'][0]['safe_value'] = check_plain($field_ref);
	
	
	//$file_name='Koala.jpg';
    $file_temp = file_get_contents($file_directorie.'\\'.$pictuure);

	// Saves a file to the specified destination and creates a database entry.
	$file_temp = file_save_data($file_temp, $file_private . $pictuure, FILE_EXISTS_RENAME);

	$node->field_pic = array(
	  'und' => array(
		0 => array(
		  'fid' => $file_temp->fid,
		  'filename' => $file_temp->filename,
		  'filemime' => $file_temp->filemime,
		  'uid' => $user->uid,
		  'uri' => $file_temp->uri,
		  'status' => 1,
		  'display' => 1
		)
	  )
	);
	
	
    node_save($node);
  }
}


function impport_import_finished() {
  drupal_set_message(t('Import Completed Successfully'));
}

?>