<?php
/**
 * Implements hook_permission()
 */
function impport_permission() {
  return array(
    'administer uploader' => array(
      'title' => t('Administer Uploader'),
      'description' => t('Allow the following roles to upload csv files to the server.'),
    ),
  );
}
 
/**
 * Implements hook_menu()
 */
function impport_menu() {
  $items['file-uploader'] = array(
    'title' => 'Upload a File',
    'type' => MENU_CALLBACK,
    'description' => 'Import a csv',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('impport_import_form'),
    'access arguments' => array('administer uploader'),
  );
  
    $items['admin/config/impport'] = array(
    'title' => 'Import CSV Config',
    'description' => 'Exemple de configuration de import CSV ',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('impport_admin_form'),
    'access arguments' => array('administer site configuration'),
    'file' => 'impport.admin.inc',
    'type' => MENU_NORMAL_ITEM,
  );
  
  $items['filter'] = array(
    'title' => 'Table Filter',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('impport_list_form'),
    'access arguments' => array("access content"),
    'type' => MENU_CALLBACK
  );

  return $items;
}


function impport_list_form($form, &$form_state) {
	
	
	  $header = array(
		array('data' => t('Nom'),'field' => 'title'),
		array('data' => t('Valeur'),'field' => 'field_valeur'),
		array('data' => t('ref'),'field' => 'field_ref'),
	  );
	  
	  
      $form = array();
		 
		$form['filter'] = array(
		  '#type' => 'fieldset',
		  '#collapsible' => TRUE,
		  '#collapsed' => FALSE,
		  '#title' => t('Filter option')
		);
		$form['filter']['filter_nom'] = array(
		  '#type' => 'select',
		  '#title' => t('Seletionez'),
		  '#options' => array('1'=>t('Nom'),'2'=>t('Valeur'),'3'=>t('All')),
		  '#default_value' => 0,
		);
		/*$form['filter']['filter_quiz'] = array(
		  '#type' => 'textfield',
		  '#title' => t('Quiz title'),
		  '#size' => 15,
		);
		$form['filter']['filter_group'] = array(
		  '#type' => 'textfield',
		  '#title' => t('Group name'),
		  '#size' => 15,
		);
		$form['filter']['submit'] = array(
		  '#type' => 'submit',
		  '#value' => t('Filter'),
		);
		*/
      	
	// Query all of the nids of a particular content type.
    $nids = db_select('node', 'n')
    ->fields('n', array('nid'))
    ->condition('type', 'accessoire', '=')
    ->execute()
    ->fetchCol();
  
    // Get all of the article nodes.
    $nodes = node_load_multiple($nids);

	
	
	$form['table'] = array(
	  '#theme' => 'myo_template',
	  '#header' => $header,
	  '#rows' => $nodes
	);
	
	//$form['results'] = theme('my_template', $vars); 
  
	//return $output;
	return $form;
  }
 
  
  
  
  function impport_theme($existing, $type, $theme, $path){
    return array(
        'myo_template' => array(
            'template' => 'myo-template',
			'variables' => array(
                'header' => NULL,
				'rows' => NULL,
            ),
        ),
    );
    }
  
  /*function impport_list_form_submit($form, &$form_state) {
  $form_state['filters']['nom'] = $form_state['values']['filter_nom'];
  }*/


/**
 * @file
 * (config_exemple.admin.inc) Exemple de formulaires de configuration
 */

function impport_admin_form($form, &$form_state) {
 
  $form['impport'] = array(
    '#type' => 'textfield',
    '#title' => 'Chemin dossier contenant image à importer',
    '#default_value' => variable_get('impport_configuration', 'C:\Users\amine\Downloads'),
    '#size' => 100,
    '#maxlength' => 128,
    '#required' => TRUE,
  );
  
  $form['impporti'] = array(
    '#type' => 'textfield',
    '#title' => 'Chemin dossier ou seront uploder les image',
    '#default_value' => variable_get('impporti_configuration', 'access/picture/'),
    '#size' => 100,
    '#maxlength' => 128,
    '#required' => TRUE,
  );
 
  $form['submit'] = array(
      '#type' => 'submit',
      '#value' => 'Mettre à jour',
      '#submit' => array('impport_admin_submit'),
  );
 
  return $form;
 
}


function impport_admin_submit($form, &$form_state) {
 
  //$variable_persitante = variable_get('impport_configuration', NULL);
  // $variable_persitante = variable_get('impport_configuration', 'C:\Users\amine\Downloads');
   //$variable_persitantes = variable_get('impporti_configuration', 'private://access/picture/');

  $valeur_transmise = $form_state['values']['impport'];
  $valeur_transmises = $form_state['values']['impporti'];
  //if ($variable_persitante != $valeur_transmise) {
    variable_set('impport_configuration', $valeur_transmise);
	variable_set('impporti_configuration', $valeur_transmises);
    drupal_set_message('Variable mise à jour avec ' . $valeur_transmise . $valeur_transmises);
  /*}
  else {
    drupal_set_message('La variable persistante est inchangée');
  }*/

}




/**
 * Builds a form that will allow users to upload csv files
 * 
 * @see
 *   hook_menu()
 */
function impport_import_form($form, $form_state) {
  $form['notes'] = array(
    '#type' => 'markup',
    '#markup' => '<div class="import-notes">A few notes when uploading. <ul><li>Make sure the file is in a .csv format.</li><li>Columns should be in *this* order</li><li>Be sure to click the "Upload" button when you select a csv.</li></ul></div>',
    '#upload_location' => 'public://tmp/',
  );
  $form['import'] = array(
    '#title' => t('Import'),
    '#type' => 'managed_file',
    '#description' => t('The uploaded csv will be imported and temporarily saved.'),
    '#upload_location' => 'public://tmp/',
    '#upload_validators' => array(
      'file_validate_extensions' => array('csv'),
    ),
  );
  $form['submit'] = array (
    '#type' => 'submit',
    '#value' => t('Import'),
  );
  return $form;
}





/**
 * Submit handler for module_name_import_form()
 */
function impport_import_form_submit($form, $form_state) {
  // Check to make sure that the file was uploaded to the server properly
  $uri = db_query("SELECT uri FROM {file_managed} WHERE fid = :fid", array(
    ':fid' => $form_state['input']['import']['fid'],
  ))->fetchField();
  if(!empty($uri)) {
    if(file_exists(drupal_realpath($uri))) { 
      // Open the csv
      $handle = fopen(drupal_realpath($uri), "r");
      // Go through each row in the csv and run a function on it. In this case we are parsing by '|' (pipe) characters.
      // If you want commas are any other character, replace the pipe with it.
      while (($data = fgetcsv($handle, 0, ',', '"')) !== FALSE) {
        $operations[] = array(
          'impport_import_batch_processing',  // The function to run on each row
          array($data),  // The row in the csv
        );
      }
 
      // Once everything is gathered and ready to be processed... well... process it!
      $batch = array(
        'title' => t('Importing CSV...'),
        'operations' => $operations,  // Runs all of the queued processes from the while loop above.
        'finished' => 'impport_import_finished', // Function to run when the import is successful
        'error_message' => t('The installation has encountered an error.'),
        'progress_message' => t('Imported @current of @total products.'),
      );
      batch_set($batch);
      fclose($handle);    
    }
  }
  else {
    drupal_set_message(t('There was an error uploading your file. Please contact a System administator.'), 'error');
  }
}



/**
 * This function runs the batch processing and creates nodes with then given information
 * @see
 * module_name_import_form_submit()
 */
function impport_import_batch_processing($data) {
	
  // Lets make the variables more readable.
  //$file_directorie='C:\Users\amine\Downloads';
  $file_directorie=variable_get('impport_configuration', 'C:\Users\amine\Downloads');
  $pathp=variable_get('impporti_configuration', 'access/picture/');
  $file_private='private://'.$pathp;
  
  $nom = $data[0];
  $field_valeur = $data[1];
  $field_ref = $data[2];
  $pictuure=$data[3];
  // Find out if the node already exists by looking up its serial number. Each serial number should be unique. You can use whatever you want.
  $nid = db_query("SELECT DISTINCT n.nid FROM {node} n " . 
    "INNER JOIN {field_data_field_ref} s ON s.revision_id = n.vid AND s.entity_id = n.nid " .
    "WHERE field_ref_value = :serial", array(
      ':serial' => $field_ref,
    ))->fetchField();
  if(!empty($nid)) {
    // The node exists! Load it.
	 global $user;
    $node = node_load($nid);
 
    // Change the values. No need to update the serial number though.
    $node->title = $nom;
    $node->field_valeur['und'][0]['value'] = $field_valeur;
    $node->field_valeur['und'][0]['safe_value'] = check_plain($field_valeur);
	
	//$file_name='Koala.jpg';
	
	$file_temp = file_get_contents($file_directorie.'\\'.$pictuure);

	// Saves a file to the specified destination and creates a database entry.
	$file_temp = file_save_data($file_temp, $file_private.$pictuure, FILE_EXISTS_RENAME);

	$node->field_pic = array(
	  'und' => array(
		0 => array(
		  'fid' => $file_temp->fid,
		  'filename' => $file_temp->filename,
		  'filemime' => $file_temp->filemime,
		  'uid' => $user->uid,
		  'uri' => $file_temp->uri,
		  'status' => 1,
		  'display' => 1
		)
	  )
	);
	

	
	
	
    node_save($node);
  }
  else {
    // The node does not exist! Create it.
    global $user;
    $node = new StdClass();
    $node->type = 'accessoire'; // Choose your type
    $node->status = 1; // Sets to published automatically, 0 will be unpublished
    $node->title = $nom;
    $node->uid = $user->uid;		
    $node->field_valeur['und'][0]['value'] = $field_valeur;
    $node->field_valeur['und'][0]['safe_value'] = check_plain($field_valeur);
    $node->language = 'und';
    
    $node->field_ref['und'][0]['value'] = $field_ref;
    $node->field_ref['und'][0]['safe_value'] = check_plain($field_ref);
	
	
	//$file_name='Koala.jpg';
    $file_temp = file_get_contents($file_directorie.'\\'.$pictuure);

	// Saves a file to the specified destination and creates a database entry.
	$file_temp = file_save_data($file_temp, $file_private . $pictuure, FILE_EXISTS_RENAME);

	$node->field_pic = array(
	  'und' => array(
		0 => array(
		  'fid' => $file_temp->fid,
		  'filename' => $file_temp->filename,
		  'filemime' => $file_temp->filemime,
		  'uid' => $user->uid,
		  'uri' => $file_temp->uri,
		  'status' => 1,
		  'display' => 1
		)
	  )
	);
	
	
    node_save($node);
  }
}


function impport_import_finished() {
  drupal_set_message(t('Import Completed Successfully'));
}

?>